### ISSUE TITLE
Issue with uploading catalog

### ISSUE THREAD

**Issue by malwahedi** [CelsoReyes/zmap7#20]
Hello

I have worked previously on older versions of Zmap. It is a wonderful tool. However, I was not able to upload a catalog to version 7. I have tried to upload it in ASCII format as .dat, .csv and .txt
All types returned error messages:

![image](https://user-images.githubusercontent.com/52782248/61041801-05ff5000-a3e4-11e9-8a82-c806382d9e22.png)
---------------------------------------------------------------------------------
2) I have tried to save the catalog in a .mat and upload through Zmap, but got the following error message:

![image](https://user-images.githubusercontent.com/52782248/61042089-9178e100-a3e4-11e9-9e8d-d24749c36003.png)

Could you please advice me.

Thanks

**Comment by CelsoReyes** [comment]
Hi Malwahedi
I'm finally back to clear out the issue queue, and appologize for the absense.  If zmap doesn't know how to interpret the files as they exist, you can help it by adding column titles to your data file(s) as a header.  Just be sure to use the same delimeters in your header as is used within the file.

Zmap looks for things like \:
  **Longitude, Latitude, Depth, Magnitude, MagnitudeType**, and **Date** 
 Dates can be of several varieties --> 
* individual columns for each part : **Year**, **Month**, **Day**, **Hour**, **Minute**, **Second**  
* a single column called **Date**, containing something like `YYYY-MM-DDTHH:MM:SS` 
* a couple columns **Date** and **Time** containing `YYYY-MM-DD` and `HH:MM:SS` respectively

A future release will have a better error message to help direct users towards the solution

Sincerely,
Celso
