### ISSUE TITLE
unable to plot Mc map

### ISSUE THREAD

**Issue by naruppert** [CelsoReyes/zmap7#23]
After running "Mc, a-, b-value map" option I am unable to select Mc map in gridresults map window. How can I plot Mc map? 
![Screen Shot 2019-08-09 at 1 48 56 PM](https://user-images.githubusercontent.com/44040775/62811120-ff302f80-baac-11e9-8a4f-ddf355cca92c.png)

**Comment by CelsoReyes** [comment]
Hi Natascha,
Sorry it took so long to get to this, I've been on another project all year.  It should be fixed with the latest commit.
Cheers,
Celso
