### ISSUE TITLE
unable to plot Fractal dimension

### ISSUE THREAD

**Issue by cyrilcs1** [CelsoReyes/zmap7#24]
I am using zmap 7.1
following error message is shown when I tried to compute fractal dimension

Undefined function 'startfd' for input arguments of type 'double'.

Error in CumTimePlot/add_cumtimeplot_zmenu/cb_computefractal (line 412)
                startfd(org);

Error in CumTimePlot>@(~,~)cb_computefractal(5) (line 355)
            uimenu(op6,'Label','Compute D for random catalog'    , msfield,
            @(~,~)cb_computefractal(5));
 
Error while evaluating Menu Callback.

**Comment by CelsoReyes** [comment]
This will be handled along with issue #19

**Comment by EmilEU** [comment]
I am using zmap 7.1 on MATLAB R2019b
following error message is shown when I tried to compute fractal dimension
Undefined function 'startfd' for input arguments of type 'double'.
Error in CumTimePlot/add_cumtimeplot_zmenu/cb_computefractal (line 412)
startfd(org);
Error in CumTimePlot>@(,)cb_computefractal(5) (line 355)
uimenu(op6,'Label','Compute D for random catalog' , msfield,
@(,)cb_computefractal(5));
Error while evaluating Menu Callback.I

**Comment by RekhaShivi** [comment]
> I am using zmap 7.1
> following error message is shown when I tried to compute fractal dimension
> 
> Undefined function 'startfd' for input arguments of type 'double'.
> 
> Error in CumTimePlot/add_cumtimeplot_zmenu/cb_computefractal (line 412)
> startfd(org);
> 
> Error in CumTimePlot>@(~,~)cb_computefractal(5) (line 355)
> uimenu(op6,'Label','Compute D for random catalog' , msfield,
> @(~,~)cb_computefractal(5));
> 
> Error while evaluating Menu Callback.

**Comment by RekhaShivi** [comment]
Undefined function 'startfd' for input arguments of type 'double'.

Error in CumTimePlot/add_cumtimeplot_zmenu/cb_computefractal (line 413)
                startfd(org);

Error in CumTimePlot>@(~,~)cb_computefractal(2) (line 355)
            uimenu(op6,'Label','Compute the fractal dimension D' , msfield, @(~,~)cb_computefractal(2));
 
Error while evaluating Menu Callback.

This error when trying to find out Fractal dimension.
